### ISSUE TITLE
om.chaquo.python.PyException: OSError

### ISSUE THREAD

**Issue by KenshinTang** [l1006986533/vits-android#1]
FATAL EXCEPTION: main
                                                                            Process: com.chaquo.myapplication, PID: 15464
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaquo.myapplication/com.chaquo.myapplication.MainActivity}: com.chaquo.python.PyException: OSError: Can't get source for <function fused_add_tanh_sigmoid_multiply at 0x75248168b0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
                                                                            	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3504)
                                                                            	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3643)
                                                                            	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                            	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
                                                                            	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
                                                                            	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
                                                                            	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                            	at android.os.Looper.loop(Looper.java:238)
                                                                            	at android.app.ActivityThread.main(ActivityThread.java:7798)
                                                                            	at java.lang.reflect.Method.invoke(Native Method)
                                                                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
                                                                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
                                                                            Caused by: com.chaquo.python.PyException: OSError: Can't get source for <function fused_add_tanh_sigmoid_multiply at 0x75248168b0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
                                                                            	at <python>.torch._utils_internal.get_source_lines_and_file(_utils_internal.py:62)
                                                                            	at <python>.torch.jit.frontend.get_jit_def(frontend.py:240)
                                                                            	at <python>.torch.jit._script.script(_script.py:986)
                                                                            	at <python>.commons.<module>(commons.py:101)
                                                                            	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                            	at <python>.app.<module>(app.py:2)
                                                                            	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
                                                                            	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
                                                                            	at <python>.java.android.importer.exec_module(importer.py:554)
                                                                            	at <python>.java.android.importer.exec_module(importer.py:606)
                                                                            	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
                                                                            	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
                                                                            	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                                                                            	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                                                                            	at <python>.importlib.import_module(__init__.py:127)
                                                                            	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                                                            	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                            	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                            	at com.chaquo.myapplication.MainActivity.onCreate(MainActivity.kt:31)
                                                                            	at android.app.Activity.performCreate(Activity.java:7963)
                                                                            	at android.app.Activity.performCreate(Activity.java:7952)
                                                                            	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
                                                                            	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3479)
                                                                            	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3643) 
                                                                            	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                            	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140) 
                                                                            	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100) 
                                                                            	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229) 
                                                                            	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                            	at android.os.Looper.loop(Looper.java:238) 
                                                                            	at android.app.ActivityThread.main(ActivityThread.java:7798) 
                                                                            	at java.lang.reflect.Method.invoke(Native Method) 
                                                                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512) 
                                                                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by KenshinTang** [comment]
resolved by change @torch.jit.script to @torch.jit._script_if_tracing
